<a href="https://colab.research.google.com/github/isissa01/Machine_Learning_With_Pytorch/blob/main/00__pytorch_fundementals_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [ ]:
#Introduction to tensors
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get scalar back as a normal number
scalar.item()


7

In [ ]:
#Vector
vector = torch.tensor([2, 4])
vector

tensor([2, 4])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape


torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7, 8],
                       [9, 0]])
MATRIX

tensor([[7, 8],
        [9, 0]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                       [ 3, 6, 9],
                       [4, 5, 3]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [4, 5, 3]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

#Random Tensors

Random tensors are important because the way that many nueral networkds learn is that they start with tensor full of random numbers then adjust those random numbers to better represent the data

In [ ]:
#Create a random tensor of size  and shape
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2491, 0.6063, 0.6316, 0.9083],
        [0.0349, 0.3195, 0.8194, 0.1689],
        [0.1046, 0.9839, 0.4455, 0.0881]])

In [ ]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(3,224,224)

In [ ]:
random_image_size_tensor.shape

torch.Size([3, 224, 224])

#Zeros and ones


In [ ]:
#create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

#Create a range of tensors and a tensors-like

In [ ]:
#Use torch.arange()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#create tensors like
ten_zeros = torch.zeros_like(one_to_ten)

In [ ]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#Float 32 tensor
float_32_tensor = torch.tensor([3., 6., 9.], dtype =None, device=None, requires_grad=False)

In [ ]:
float_32_tensor

tensor([3., 6., 9.])